addSbtPlugin("com.eed3si9n"       % "sbt-buildinfo"                 % "0.13.1")
addSbtPlugin("com.github.sbt"     % "sbt-unidoc"                    % "0.6.0")
addSbtPlugin("com.github.sbt"     % "sbt-ci-release"                % "1.11.2")
addSbtPlugin("com.github.cb372"   % "sbt-explicit-dependencies"     % "0.2.16")
addSbtPlugin("org.portable-scala" % "sbt-scalajs-crossproject"      % "1.3.2")
addSbtPlugin("org.scala-js"       % "sbt-scalajs"                   % "1.20.1")
addSbtPlugin("org.portable-scala" % "sbt-scala-native-crossproject" % "1.3.2")
addSbtPlugin("org.scala-native"   % "sbt-scala-native"              % "0.5.9")
addSbtPlugin("org.scalameta"      % "sbt-mdoc"                      % "2.8.0")
addSbtPlugin("org.scalameta"      % "sbt-scalafmt"                  % "2.5.6")
addSbtPlugin("org.scoverage"      % "sbt-scoverage"                 % "2.4.0")
addSbtPlugin("org.scalameta"      % "sbt-native-image"              % "0.3.2")
addSbtPlugin("dev.zio"            % "zio-sbt-website"               % "0.4.0")
addSbtPlugin("ch.epfl.scala"      % "sbt-scalafix"                  % "0.14.4")

resolvers += Resolver.sonatypeRepo("public")
